-- !Ups
CREATE TABLE "USERS" (
  "ID" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "FIRST_NAME" VARCHAR(255) NOT NULL,
  "MIDDLE_NAME" VARCHAR(255),
  "LAST_NAME" VARCHAR(255),
  "USERNAME" VARCHAR(255),
  "EMAIL" VARCHAR(255),
  "PASSWORD" VARCHAR(255)
);


-- !Downs
DROP TABLE "USERS";
